/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mist({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mist.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube025.geometry} material={materials.white} position={[0, 0.93, 0]} rotation={[0, -0.31, 0]} scale={[4.97, 0.23, 0.23]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials.white} position={[0, 0.05, 0]} rotation={[0, -0.12, 0]} scale={[7.21, 0.23, 0.23]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.white} position={[0, -1.12, 0]} rotation={[0, 0.08, 0]} scale={[9.15, 0.23, 0.23]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials.white} position={[0, -2.3, 0]} rotation={[0, -0.48, 0]} scale={[7.21, 0.23, 0.23]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials.white} position={[0, -4.77, 0]} rotation={[0, 0.28, 0]} scale={[4.97, 0.23, 0.23]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.white} position={[0, -3.54, 0]} rotation={[0, -0.09, 0]} scale={[2.59, 0.23, 0.23]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials.white} position={[0, 2.03, 0]} rotation={[0, 0.15, 0]} scale={[2.59, 0.23, 0.23]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials.white} position={[0, -0.53, 0]} rotation={[0, 0.15, 0]} scale={[2.59, 0.23, 0.23]} />
    </group>
  )
}

useGLTF.preload('/mist.glb')
