/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Snow({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/snow.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube004.geometry} material={materials.white} position={[0.43, 3.22, -7.68]} rotation={[0, -0.53, 0]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.white} position={[9.39, 6.3, -1.76]} rotation={[0, 1.34, 0]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.white} position={[9.64, 0, 8.08]} rotation={[0, 0.52, 0]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials.white} position={[5.33, 7.05, -0.89]} rotation={[0, -0.25, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.white} position={[4.59, -0.03, -5.47]} rotation={[0, 0.63, 0]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials.white} position={[-5.11, 4.11, 5.35]} rotation={[0, 0.21, 0]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials.white} position={[1.34, 6.3, 5.76]} rotation={[0, -0.29, 0]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials.white} position={[-9.07, 3.68, -5.78]} rotation={[0, 0.39, 0]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials.white} position={[-6.28, 0.91, -0.56]} rotation={[0, -0.33, 0]} />
      <mesh geometry={nodes.Cube049.geometry} material={materials.white} position={[-13.28, 1.04, 2.94]} rotation={[0, -0.45, 0]} />
      <mesh geometry={nodes.snow.geometry} material={materials.white} position={[10.99, 1.77, -1.1]} rotation={[0, -0.57, 0]} scale={[1.3, 0.07, 0.07]} />
      <mesh geometry={nodes.snow001.geometry} material={materials.white} position={[5.42, -2.76, -6.65]} rotation={[0, 0.17, 0]} scale={[1.3, 0.07, 0.07]} />
      <mesh geometry={nodes.snow002.geometry} material={materials.white} position={[-6.89, -2.71, -0.72]} rotation={[0, -1.02, 0]} scale={[1.3, 0.07, 0.07]} />
      <mesh geometry={nodes.snow003.geometry} material={materials.white} position={[-5.72, -2.71, 5.19]} rotation={[Math.PI, -1.35, Math.PI]} scale={[1.3, 0.07, 0.07]} />
      <mesh geometry={nodes.snow004.geometry} material={materials.white} position={[0.83, 1.48, 6.9]} rotation={[0, 0.52, 0]} scale={[1.3, 0.07, 0.07]} />
    </group>
  )
}

useGLTF.preload('/snow.glb')
